### ISSUE TITLE
bytearrays have changed in Python so the code is broken

### ISSUE THREAD

**Issue by Velek** [etdey/gdl90#5]
I'm not a Python expert.  I think I've hacked the code to work, but I'm not a GDL90 expert either, so I'm not sure if I've broken the messages on the wire either.
My Python interpreter also wants parens in the print statements too.

**Comment by etdey** [comment]
Thanks, Velek. I think you are seeing Python 2 vs. 3 incompatibilities. I am in the process of converting this code base to support Python 3 and, if you want a preview of that, you can checkout the `2023/python3-conversion` branch.

**Comment by etdey** [comment]
I just merged the Python3 conversion updates into the `master` branch.

**Comment by etdey** [comment]
I just merged the Python3 conversion updates into the master branch.

**Comment by Velek** [comment]
Thanks!
I'm still getting errors.
I need to add encoding="utf-8' here:
./simulate_stratux.py 
Simulating Stratux unit.
Transmitting to 10.1.1.255:4000
Traceback (most recent call last):
  File "/Users/ek/Projects/gdl90/./simulate_stratux.py", line 131, in <module>
    buf = encoder.msgSXHeartbeat(towers=towers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ek/Projects/gdl90/gdl90/encoder.py", line 234, in msgSXHeartbeat
    msg = bytearray(chr(0x1d))
          ^^^^^^^^^^^^^^^^^^^^
TypeError: string argument without an encoding

After changing to utf-8
        """message ID #29 for Hiltonsoftware SX heartbeat"""

        msg = bytearray(chr(0x1D), encoding="utf-8")

 I get stuck at the struct.pack() :
./simulate_stratux.py 
Simulating Stratux unit.
Transmitting to 10.1.1.255:4000
Traceback (most recent call last):
  File "/Users/ek/Projects/gdl90/./simulate_stratux.py", line 131, in <module>
    buf = encoder.msgSXHeartbeat(towers=towers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ek/Projects/gdl90/gdl90/encoder.py", line 335, in msgSXHeartbeat
    struct.pack(
struct.error: char format requires a bytes object of length 1

**Comment by etdey** [comment]
Thanks. I missed these messages in the conversion and pushed updates today that should resolve them. I removed the two old device-specific simulators and replaced them with a unified one called: `simulate_gdl90_unit.py`. 

Try this: `./simulate_gdl90_unit.py -v --subnetbcast`

If you are using an EFB that recognizes a Stratux device, that will create an ownship that flies in a large circle with 12 "bandit" traffic targets that fly the same circle in the opposite direction.

**Comment by etdey** [comment]
Velek, did that work for you?

**Comment by Velek** [comment]
I haven't been feeling well the past couple of days.
I'll let you know when I'm well enough to check it out.
Thanks!
